# Generated by Django 2.0 on 2017-12-19 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoosePicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='../app/static/app/photos')),
            ],
        ),
        migrations.DeleteModel(
            name='ImageUploadModel',
        ),
    ]
