# Generated by Django 2.0 on 2017-12-20 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20171219_1916'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChoosePicture',
            new_name='ExampleModel',
        ),
        migrations.RenameField(
            model_name='examplemodel',
            old_name='image',
            new_name='model_pic',
        ),
    ]
