# Generated by Django 2.0 on 2017-12-20 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20171220_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagePostModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='app/static/app/photos/')),
                ('uploaded_by', models.CharField(blank=True, max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ExampleModel',
        ),
    ]
