# Generated by Django 2.0 on 2018-01-04 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_likes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Likes',
        ),
        migrations.AddField(
            model_name='imagepostmodel',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
