# Generated by Django 2.0 on 2018-01-05 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20180104_2114'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.RemoveField(
            model_name='imagepostmodel',
            name='time',
        ),
    ]
