# Generated by Django 2.0 on 2018-01-05 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='Comment',
            new_name='comment',
        ),
    ]
